### ISSUE TITLE
Feature Request: Add CPL for PCB Fab

### ISSUE THREAD

**Issue by CountParadox** [petl/USB-C-cable-tester-C2C-caberQU#2]
Hi friend, 

Is it possible to add / generate a CPL file for sending to PCB Fab place like JLCPCB? 

I want to have a batch of 30-50 of these made up, your Tindie store ran out of stock as I bought a few..
But I was hoping to avoid the SMT soldering myself..

Would it be possible to generate a file from the software you used to design it?

**Comment by CountParadox** [comment]
JLC Has a number of articles showing how you could generate one in the software you used!

https://support.jlcpcb.com/category/78-smt-assembly

**Comment by petl** [comment]
Hey, 
I can send you a few boards, no problem, just write me a PM. I just want to avoid others selling this, as there is a Kickstarter campaign still on its way. If you have a bit more time, the tindie store will be stocked for sure.

**Comment by CountParadox** [comment]
I'm not sure how to pm on GitHub...
I'm not looking to sell them, just get a bulk load for my co workers :) we go through a lot of USB C cables

**Comment by CountParadox** [comment]
I did a jlcpcb order of 15 PCB as test; for anyone interested soldering by hand wasn't too hard. Took about 20 minutes for one board with an iron and smd rework station. 

A form of the project has the BOM so you can order the correct parts from lscs. Was about $20 for the parts for $15 and $20 for the 15 PCBs. 

For the remaining 14 I will use my local makerspace's smd oven to do 6-8 at once and smash the others out in an hour....

Still think it's weird for the designer to offer the Gerber's but not want people to make their own?

**Comment by CountParadox** [comment]
![received_1019783695367992.jpeg](https://user-images.githubusercontent.com/6279380/183845074-b01110e1-2c6e-40cb-83cf-6f4d0d0fad39.jpeg)

![received_3265281097126188.jpeg](https://user-images.githubusercontent.com/6279380/183845092-83116ece-0807-494e-a05b-52675a0a129e.jpeg)

![20220810_172929.jpg](https://user-images.githubusercontent.com/6279380/183845103-dbdbd0ee-b8bd-40ee-839f-3994b22e85e8.jpg)

![20220810_172924.jpg](https://user-images.githubusercontent.com/6279380/183845124-3d203511-6d9a-4a00-a433-77da9b6c7e29.jpg)

![20220810_172920.jpg](https://user-images.githubusercontent.com/6279380/183845143-f920f732-e72f-4419-a098-8efed8996f73.jpg)

**Comment by OSHM34** [comment]
Good morning Lewys,

I'm, kind an of oldie 👴🏻,  electronics hobbyist.

I'm not sure if I understood correctly but if possible I would love to have
two of those boards.

If possible kindly advise how to proceed, have to pay etc.

Warm regards,
Hakan

**Comment by petl** [comment]
> I did a jlcpcb order of 15 PCB as test; for anyone interested soldering by hand wasn't too hard. Took about 20 minutes for one board with an iron and smd rework station.
> 
> A form of the project has the BOM so you can order the correct parts from lscs. Was about $20 for the parts for $15 and $20 for the 15 PCBs.
> 
> For the remaining 14 I will use my local makerspace's smd oven to do 6-8 at once and smash the others out in an hour....
> 
> Still think it's weird for the designer to offer the Gerber's but not want people to make their own?

Thanks for the feedback, the photos look great! I really like that all the necessary files are there and useful. 
The p'n'p files are not there for the obvious reason that I would like to deter copycats from cloning the thing and selling it on e-bay/ali/.... I would like to enable people making a couple of units at home, that's why this repo exists, to give something back to the community.

I will continue to push newer updates and files to github in order for you to have the best possible experience with the C2C caberQU. Thanks for the forks, pull requests and propositions to make things better!

**Comment by CountParadox** [comment]
I have since recreated the board in kicad and have generated  pnp files. contemplating if I should share them to my own repo..
I was able to order 20 boards fully assembled for around $30
