### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [petl/USB-C-cable-tester-C2C-caberQU#4]
Hello!

I found this project from https://hackaday.com/2023/08/11/usb-c-cable-tester-is-compact-and-affordable/

Could you please add information about the license of this repository — is it allowed to copy, change and use the code, documentation and design files in any purpose?
It would be great to see any popular open source license.

**Comment by petl** [comment]
Hey, 

thanks for letting me know. The licensing variant as it is now is sufficient I think: please don't make commercial copies of this.

**Comment by vazhnov** [comment]
I don't see any change in the project. The last commit is still Jan 14, 2023. @petl, maybe you forgot to push the changes?

**Comment by petl** [comment]
Don't do commercial copies, that's pretty much it, a license is not really needed.
