### ISSUE TITLE
Clarify documentation to reflect USB 3.2 Gens please ...

### ISSUE THREAD

**Issue by gjashley** [petl/USB-C-cable-tester-C2C-caberQU#5]
... i.e. 3.2 Gen 1, 3.2Gen 2x1, 3.2 Gen 2x2 (also 4 and Thunderbolt if that can be derived from the cable)
I'm so confused :/

**Comment by petl** [comment]
USB generations are not really clear and have unfortunately been changed by the USB foundation quite often. The unit can differentiate if the pins are available, but not if a certain speed can or is actually used by the connected devices.
