### ISSUE TITLE
Futureproof? 

### ISSUE THREAD

**Issue by thibaultmol** [petl/USB-C-cable-tester-C2C-caberQU#6]
I was wondering when USB 4.1 or 5 whatever comes out, will this device just say "it's usb 4"? 

also what happens with thunderbolt cables?

**Comment by petl** [comment]
Please refer to the documentation about the supported pinouts and how to read them: https://github.com/petl/USB-C-cable-tester-C2C-caberQU/tree/main/documentation/v3

If you'd like to have an updated version, I would recommend to subscribe to our newsletter or social media, we have something in the pipeline ;)
